import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faQrcode,
  faCreditCard,
  faBarcode,
  faUser,
  faWallet,
  faAngleDoubleLeft,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleRight,
  faArrowUp,
  faSignOutAlt,
  faTrash,
  faExternalLinkAlt,
  faBars,
  faShoppingCart,
  faBox,
  faChartBar,
  faImage,
  faCheckCircle,
  faHourglassHalf,
  faTimesCircle,
  faExclamationTriangle,
  faCalendar,
  faCalendarAlt,
  faCalendarTimes,
  faMoneyBillWave,
  faClipboardList,
  faPlus,
  faEdit,
  faList,
  faInfoCircle,
  faSave,
  faCrop,
  faBoxOpen,
  faUserCheck,
  faCheck,
  faEye,
  faPrint,
  faClock,
  faTicketAlt,
  } from '@fortawesome/free-solid-svg-icons'

import { faPix } from '@fortawesome/free-brands-svg-icons'

library.add(
  faQrcode,
  faCreditCard,
  faBarcode,
  faUser,
  faWallet,
  faPix,
  faAngleDoubleLeft,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleRight,
  faArrowUp,
  faSignOutAlt,
  faTrash,
  faExternalLinkAlt,
  faBars,
  faShoppingCart,
  faBox,
  faChartBar,
  faImage,
  faCheckCircle,
  faHourglassHalf,
  faTimesCircle,
  faExclamationTriangle,
  faCalendar,
  faCalendarAlt,
  faCalendarTimes,
  faMoneyBillWave,
  faClipboardList,
  faPlus,
  faEdit,
  faList,
  faInfoCircle,
  faSave,
  faCrop,
  faBoxOpen,
  faUserCheck,
  faCheck,
  faEye,
  faPrint,
  faClock,
  faTicketAlt,
)

export { FontAwesomeIcon }
